# Generated by Django 5.0.6 on 2024-05-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
    ]
