# Generated by Django 5.0.6 on 2024-06-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0008_children_uploadfiles_alter_category_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Children",
        ),
    ]
