# Generated by Django 5.0.6 on 2024-06-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0009_delete_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfiles",
            name="file",
            field=models.FileField(upload_to="../uploads_model"),
        ),
    ]
