# Generated by Django 5.0.6 on 2024-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0011_alter_uploadfiles_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfiles",
            name="file",
            field=models.FileField(upload_to="./youtube-lesson/uploads_model"),
        ),
    ]
