# Generated by Django 5.0.6 on 2024-06-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0013_women_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfiles",
            name="file",
            field=models.FileField(upload_to="uploads_model"),
        ),
    ]
