# Generated by Django 5.0.6 on 2024-06-04 08:15

import women.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0014_alter_uploadfiles_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagpost",
            options={
                "verbose_name": "Тег категорий",
                "verbose_name_plural": "Теги категорий",
            },
        ),
        migrations.AlterField(
            model_name="tagpost",
            name="tag",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Тэг"),
        ),
        migrations.AlterField(
            model_name="uploadfiles",
            name="file",
            field=models.FileField(upload_to=women.models.path_and_rename),
        ),
    ]
