# Generated by Django 5.0.6 on 2024-06-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0015_alter_tagpost_options_alter_tagpost_tag_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagpost",
            options={
                "ordering": ["tag"],
                "verbose_name": "Тег категорий",
                "verbose_name_plural": "Теги категорий",
            },
        ),
        migrations.AlterModelOptions(
            name="women",
            options={
                "ordering": ["-time_create"],
                "verbose_name": "Известные женщины",
                "verbose_name_plural": "Известные женщины",
            },
        ),
    ]
