# Generated by Django 5.0.6 on 2024-06-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0017_titledefault"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titledefault",
            options={"managed": False},
        ),
    ]
