# Generated by Django 5.0.6 on 2024-06-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0018_alter_titledefault_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titledefault",
            options={},
        ),
    ]
