# Generated by Django 5.0.6 on 2024-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0019_alter_titledefault_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titledefault",
            options={
                "verbose_name": "Настройка сайта по умолчанию",
                "verbose_name_plural": "Настройки сайта по умолчанию",
            },
        ),
        migrations.RemoveField(
            model_name="titledefault",
            name="meta_tags_default",
        ),
        migrations.AddField(
            model_name="titledefault",
            name="description_default",
            field=models.CharField(default=1, verbose_name="description по умолчанию"),
            preserve_default=False,
        ),
    ]
