# Generated by Django 5.0.6 on 2024-06-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0020_alter_titledefault_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="titledefault",
            name="keywords_default",
            field=models.CharField(
                default=1, verbose_name="ключивые слова по умолчанию"
            ),
            preserve_default=False,
        ),
    ]
